### ISSUE TITLE
Moodle. 3.9 | issue new release version Moodle.org v7.0.22.01 (2021112901)

### ISSUE THREAD

**Issue by gemguardian** [Wunderbyte-GmbH/moodle-mod_booking#191]
@atlet  and @dasistwas 
This version seems to been released onMoodle.org (https://moodle.org/plugins/mod_booking/versions)

We have an issue now is named "rating" but before was the Moodle Grade/Grading option
image

With this option we could grade students per bookingoption.
Right now we still see in the top "Rating" (wat used to be grading).

But when we select the grade (1), select the student (2) and click on "Rate" (3)nothing seems to be happening anymore
image

We dont'see a grade at "sum of ratings" and we don't see a grade in the Moodle gradebook.
This functionality seems to be broken now..

We would be really appriciate it if this could be fixed a.s.a.p. since we relay on this functionality.

As an extra note, the select option in the colum list does not seem to function either. Before it was when I clicked on this, all rows where selected.

image

Hope to hear from you as soon as possible.
gemma

**Comment by dasistwas** [comment]
@bernhard-wunderbyte seems to be a JavaScript issue. On the manage all answers page JS does not work at all.

**Comment by bernhard-wunderbyte** [comment]
@dasistwas Fixed in Booking v7.0.22.02 (2021112902).

**Comment by gemguardian** [comment]
@bernhard-wunderbyte when will this version be available on moodle.org?

**Comment by bernhard-wunderbyte** [comment]
@dasistwas will do this asap

**Comment by dasistwas** [comment]
Just published.

**Comment by gemguardian** [comment]
@dasistwas  @bernhard-wunderbyte the issue has party been resolved. 
The Rating still does not work. 

![2022-06-10_11-48-02](https://user-images.githubusercontent.com/16559999/173039481-ff2fe5ba-af26-4a2a-bbea-8e62a0de2432.gif)

**Comment by dasistwas** [comment]
@gemguardian concerning the rating: You can't rate yourself, you have to choose users that are not the same as the logged in user.

**Comment by gemguardian** [comment]
@dasistwas I forgot that :) it works that's why I deleted
