### ISSUE TITLE
Testing enrollink function

### ISSUE THREAD

**Issue by eynimeni** [Wunderbyte-GmbH/moodle-mod_booking#711]
#650 
There is a new option for bookingoptions: We can generate autoenrollinks to be enroled into a corresponding moodle course.

Steps to achieve this:
1) In the settings of bookingoptions, set define a related course

![Screenshot 2024-11-19 at 14 44 55](https://github.com/user-attachments/assets/5abad726-5dc8-43aa-b5d1-ea8a00828c96)
2) In  Availability conditions, define "Form needs to be filled out before booking": Select _Automatically enrol users_ 
Set a Label and a default value.

![Screenshot 2024-11-19 at 15 06 08](https://github.com/user-attachments/assets/2cd74670-758b-419b-9327-09188267b351)

3) Save Bookingoption 
 -> Test: If 2) and no course defined (1) there should be a validation error.

4) Define Bookingrule: 
Listen to event enrollink_triggered
![Screenshot 2024-11-19 at 15 07 44](https://github.com/user-attachments/assets/0dc13e9d-8ccc-4700-94c1-30ca3dbb3ef3)

Use placeholder {enrollink} & {qrenrollink} & {customform}
![Screenshot 2024-11-19 at 15 32 31](https://github.com/user-attachments/assets/7e5ebb83-5cbe-44b5-8366-da4a3d5d5a63)

4) Select Option: Price of bookingoption should be multiplied with number of options from form when clicked on continue. (Bookingfee is added only once.) For example, we enter "3".

5) Book bookingoption

6) See updated of booked places in bookingoption (corresponding to number defined in form) (for example 3)

7) Trigger cron

8) Recieve Mail as defined in rules

9) Mail should contain link & qr code
![Screenshot 2024-11-19 at 15 32 10](https://github.com/user-attachments/assets/d6fe38e0-4864-4457-b4c3-2c590c5e8266)

10) When clicked on Link, response depends on users and consumed seats:
- user not logged in -> redirect to login
- user not yet enroled in course & free seats (in our case, less than 3 enrolments from this link): confirmation and link to course, consumes 1 seat
- user already enroled in course: confirmation and link to course, doesn't consume seat
- if 3 (following our example) users got enroled, error that no more seats are available
- wrong param in url: errormessage

**Comment by semteacher** [comment]
Have started with behat.
@eynimeni about:

> -> Test: If 2) and no course defined (1) there should be a validation error.

Not working . Appears only for 2nd editing session:
- I can add availability condition and save option without connected course.
- when I opren it for edition again and trying to save - only at this point I get validation error.

**Comment by eynimeni** [comment]
> Have started with behat. @eynimeni about:
> 
> > -> Test: If 2) and no course defined (1) there should be a validation error.
> 
> Not working . Appears only for 2nd editing session:
> 
> * I can add availability condition and save option without connected course.
> * when I opren it for edition again and trying to save - only at this point I get validation error.

ok, thank you for finding this. we accept for the moment, that validation doesn't work correctly on creation of bookingoption. I have added an information alert.
please adapt this test and proceed with the following. thank you!

**Comment by semteacher** [comment]
Tests stauses:
- behat: covers up to step 9 (inclusively)
- phpunit: full coverage

A bug fixed in [6dfd611](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/commit/6dfd6117560e0a7045b19e65a4dfdc2835e69aca) 

Potential issue: the Gurst user can book option via enrollink (see it in the [25f2f1b](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/commit/25f2f1b6164ea916bd281e699e926b6491762b20)). Is it correct @eynimeni  @georgmaisser ?

**Comment by semteacher** [comment]
@eynimeni tried to fix phpunit on enrollink and prepare it to cover new features. Made adjustments to behat and 1 bugfix whucg affects processing of waitinglist. Hovewer:
- in case if user already enrolled. status changed from
MOD_BOOKING_AUTOENROL_STATUS_ALREADY_ENROLLED
to
MOD_BOOKING_AUTOENROL_STATUS_SUCCESS
Is it OK? Yes, still no consumption. 
- looks more seriously
$enrollink->free_places_left()
always return same walue after successfull $enrollink->enrol_user : like no consumption (see comments in code)
Note that I have tried ti disable both waitinglists (for user who buy and for users who use enrollinks)
- also it looks like still possible for the Moodle Guest user to use enrollink

**Comment by eynimeni** [comment]
_in case if user already enrolled. status changed from
MOD_BOOKING_AUTOENROL_STATUS_ALREADY_ENROLLED
to
MOD_BOOKING_AUTOENROL_STATUS_SUCCESS
Is it OK? Yes, still no consumption._
was an error, is fixed now

_$enrollink->free_places_left()
always return same walue after successfull $enrollink->enrol_user : like no consumption (see comments in code)
Note that I have tried ti disable both waitinglists (for user who buy and for users who use enrollinks)_
was an error is fixed now

_also it looks like still possible for the Moodle Guest user to use enrollink_
guests should not be able to access these functions. But I still added an additional check and adapted the tests.

@semteacher could you please extend the behat scenarios to make sure, users need to be logged in to access the enrollink? after this I think everything is tested! thank you for your efforts!

**Comment by semteacher** [comment]
@eynimeni 
1. I noticed that enrollink's behat failed at GitHub. The error message 
`"Custom message A message e-mail with subject "Enrollinksubj" has been sent to user: "Teacher 1" by the user "Teacher 1"" text was not found in the page`
sounds like message was not sent at all. But it does works OK at my local dev so tests passed OK. Again - cannot explain reason of this failure. 
2. I do not see any quick way to extend behat test on enrollink. The problem is related to incomplete MDL-75971 - Behat still cannot handle emails properly. 
Currently enrollink being sent via email. If it would be also sent via Moodle messaging feature - it shoul be possible to re-sent such message from teacher to student than login as student and follow link. But now I do not see a way to do this.
I have looked into db/message.php with intention to set message providers by default - but only one - 'sendmessages' available there and it looks like not being in use. Besides, as I understand form code - system`s ` message_send()` function still has to be used. I have tired to debug enrollink messaging but failed to catch it.... 
Finally, I know  that part of messages has been sent directly as email using email_to_user() function. Emang them are messages initiated from option->sync_waiting_list(). Those definitely cannot be tested until MDL-75971 will be resolved... 

PS: of course I have seen custom message class - but still cannot understand  why with usage of message_send() I cannot set messages to be send via Moodle messaging as well... It it would be possible - it will be make testing / debugging more easy

Therefore, as coseqence of the above - testing of actual processing of enrollink methods (like $enrollink->enrol_user()) now possible only via phpunit. Current test test_rule_on_enrollink_and_enroll() supoort only configuration with waitinlists are OFF. I think it will be becessary to extend or create another test to support waitinglist ON case. Probably it will need to made refactoring of this test too according blueprint prepared and recommended by @georgmaisser but it will take some time due to cmplexiti of this test...

**Comment by georgmaisser** [comment]
Hi, I would suspend all work with behat when it comes to checking for mails. obviously, with the enrollink this becomes harder.

BUT you could also check on the report.php the show messages table.
It's just another place and also renders from the logstore events table, so not sure if this helps. It will allow you to check messages without having to access mailpit or such.


![Image](https://github.com/user-attachments/assets/6f11cb8f-f1b8-427c-ae74-de063a0df3cd)

**Comment by semteacher** [comment]
@georgmaisser Currently I have relayed only on logstore when evaluating email. Thank you for pointing me to the report.php
Unfortunately - last failure again looks like a github-specific  one (it would be fine to know if this test works on your VMs like it is OK on my).

**Comment by semteacher** [comment]
@eynimeni I have tried to add behat and phpunit for case when both waitinglist have enabled.
- behat: the error you mentioned at the end of your video still persist (if admin/booking manager confirm themself on waitinglist - no price appears, they just booked)
- phpunit: check TODO comments in the code of test_rule_on_enrollink_and_enroll_via_waitinglists() method. Mostly the same - no price / cartitem for admin/booking manaher

**Comment by eynimeni** [comment]
ok I will check.
but for the first point "admin/booking manager confirm themself": the checkbox in enrollink area (availability conditions - form needs to be filled) applies only for users clicking on the link. to restrict access for user who buys, we need the additional checkbox "Book only after confirmation" in advanced options.

**Comment by eynimeni** [comment]
regarding extending the behat tests: I only meant to extend for users not logged in trying to click on the enrollink if the redirect is correct
of course it would also be great to check the report.php for mails sent (once cron was executed)
but it's not very important as I am sure that this is done correctly

**Comment by semteacher** [comment]
@eynimeni 

> "to restrict access for user who buys, we need the additional checkbox "Book only after confirmation" in advanced options."

I am talking exactly about this. I did this and faced same behavior as in your video were you have admitted that it is incorrect (and I agree) So this issue still present.

**Comment by eynimeni** [comment]
@semteacher I have fixed the error with confirmation of waitinglist from first user (paying for the bundle)
I have also made an adjustment to your test: when user is confirmed from waitinglist, the status in user_submit_response is different
so in the unit test, user is now confirmed from waitinglist but needs to actually purchase the bundle. then there will be free seats. I've added comments in the tests.
thank you again for your work, this is very precious to cover all kind of cases and find all kind of errors!

**Comment by semteacher** [comment]
@eynimeni I have completed behat test (that with waitinglist) but still have isses with phpunit:

> line 528 TODO: Buy this item to make sure, a new erlid bundle is created.

How I can do this? do not see suitable method in the enrollink class. Read DB? But it returns nothing - 0 records (it is how phpunit works with DB)
line 601  TODO: This is the same bundle as in the previous test. Items are already consumed. Make sure to use new bundle bought in line 528.
In my understanding - it is yet another cache issue. bundle form previous test should not exist in the following. But such as we faced similar issues few times - I think it is necessary to unset enrollink cache explicitly. I have tired 
    public static function destroy_instances() {
        self::$instances = null;
        return true;
    }  
in the enrollink class (i n the last commit) but it does not help for some reasons.  However - correct bundle definitely being generated (1st in the list) and avaialable among the $enrollink->instances:

![Image](https://github.com/user-attachments/assets/214e63e4-71d5-482f-9692-79bbdf3cc8a5)

when incorrect (2nd ) has been selected (because it was selected to the message as well).  
How to reset $enrollink->instances in the correct way?

**Comment by semteacher** [comment]
@eynimeni please check TODO comments in the code.
Now another case - free_places_left() not decreased for students comes through waitinglist...
Also - it seems that my proposal for  destroy_instances in the enrollink is not necessary. 
Debugging shown me that recent failure comes from adhock tasks preserved between tests. 
@runTestsInSeparateProcesses solve this (but add issue with debugging)

**Comment by semteacher** [comment]
Current satatus:
- phpunt: covers all features of the actual version of code.
- behat: point 10 cannot be covered until Moodle will work with MailPit OR it will be possible to send messages via Moodle's internal messaging system by default.
@georgmaisser should I close tis issue or keep it open?
